# Generated by Django 3.1.7 on 2021-04-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accDefRate', models.FloatField(blank=True, db_column='accDefRate', max_length=15, null=True)),
                ('accExamCnt', models.IntegerField(blank=True, db_column='accExamCnt', max_length=4, null=True)),
                ('accExamCompCnt', models.IntegerField(blank=True, db_column='accExamCompCnt', max_length=4, null=True)),
                ('careCnt', models.IntegerField(blank=True, db_column='careCnt', max_length=4, null=True)),
                ('clearCnt', models.IntegerField(blank=True, db_column='clearCnt', max_length=4, null=True)),
                ('createDt', models.DateTimeField(blank=True, db_column='createDt', null=True)),
                ('deathCnt', models.IntegerField(blank=True, db_column='deathCnt', max_length=4, null=True)),
                ('decideCnt', models.IntegerField(blank=True, db_column='decideCnt', max_length=4, null=True)),
                ('examCnt', models.IntegerField(blank=True, db_column='examCnt', max_length=4, null=True)),
                ('resutlNegCnt', models.IntegerField(blank=True, db_column='resutlNegCnt', max_length=4, null=True)),
                ('seq', models.IntegerField(blank=True, db_column='seq', max_length=4, null=True)),
                ('stateDt', models.DateField(blank=True, db_column='stateDt', null=True)),
                ('stateTime', models.TimeField(blank=True, db_column='stateTime', null=True)),
                ('updateDt', models.DateTimeField(blank=True, db_column='updateDt', null=True)),
            ],
        ),
    ]
